### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'before_cleanup_url'

### ISSUE THREAD

**Issue by 2br-2b** [nextcloud/news-updater#48]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Hello!

I'm trying to update my news feeds in a kubernetes cronjob, but I'm getting an error:

```
025-06-19 11:45:33,647 - Nextcloud News Updater - INFO - Running update in an interval of 300 seconds using 10 threads
2025-06-19 11:45:33,647 - Nextcloud News Updater - ERROR - 'NoneType' object has no attribute 'before_cleanup_url': Trying again in 30 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/nextcloud_news_updater/api/updater.py", line 69, in run
    self.before_update()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/nextcloud_news_updater/api/web.py", line 75, in before_update
    'Calling before update url:  %s' % self.api.before_cleanup_url)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'before_cleanup_url'
2025-06-19 11:46:03,659 - Nextcloud News Updater - ERROR - 'NoneType' object has no attribute 'before_cleanup_url': Trying again in 30 seconds
```

Here's my kubernetes cronjob task (yes I know it shouldn't be a cronjob, but I'll fix that later):

```yaml
kind: NetworkPolicy
metadata:
  name: news-updater-egress
  namespace: nextcloud
spec:
  podSelector:
    matchLabels:
      app: news-updater
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: nextcloud
      ports:
        - protocol: TCP
          port: 443
    # 2. Allow DNS
    - to:
      - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # 3. Allow PyPI (fallback: all internet)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443

---
# 3) CronJob to drive the feed updater
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-news-updater
  namespace: nextcloud
  annotations:
    # tell Keel to auto-update the container image
    keel.sh/policy: all
spec:
  schedule: "*/5 * * * *"                 # every 5 minutes
  concurrencyPolicy: Replace              # don’t pile up runs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: news-updater
        spec:
          restartPolicy: OnFailure
          containers:
            - name: news-updater
              image: python:3-slim
              imagePullPolicy: IfNotPresent
              # install the updater and invoke it against your Nextcloud app API
              command:
                - sh
                - -c
                - |
                  pip install --no-cache-dir nextcloud_news_updater && \
                  nextcloud-news-updater https://nextcloud.nextcloud.svc.cluster.local/index.php/ \
                    --user "${NC_USER}" \
                    --password "${NC_PASS}" \
                    --interval 300 \
                    --loglevel info
              env:
                - name: NC_USER
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-news-updater
                      key: NC_USER
                - name: NC_PASS
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-news-updater
                      key: NC_PASS
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"
          # no probes on a CronJob pod
```
